"""
城市拼音 → 中文映射表 + 城市等级
覆盖原始数据中所有 URL 提取到的城市拼音变体
"""

CITY_PINYIN_MAP = {
    # ===== 上海 =====
    'shanghai': '上海',
    'shanghai-xhq': '上海',
    'shanghai-cnq': '上海',
    'shanghai-pdxq': '上海',
    'shanghai-jaq': '上海',
    'shanghai-mhq': '上海',
    'shanghai-qpq': '上海',
    'shanghai-sjq': '上海',
    'shanghai-hpq': '上海',
    'shanghai-hkq': '上海',
    'shanghai-ptq': '上海',
    'shanghai-ypq': '上海',
    'shanghai-jsq': '上海',
    'shanghai-ftq': '上海',
    'shanghai-jdq': '上海',
    'shanghai-fxq': '上海',

    # ===== 北京 =====
    'beijing': '北京',
    'beijing-cpq': '北京',
    'beijing-dcq': '北京',
    'beijing-cyq': '北京',
    'beijing-xcq': '北京',
    'beijing-ftq': '北京',
    'beijing-hdq': '北京',
    'beijing-syq': '北京',
    'beijing-dxq': '北京',

    # ===== 深圳 =====
    'shenzhen': '深圳',
    'shenzhen-ftq': '深圳',
    'shenzhen-lhq': '深圳',
    'shenzhen-nsq': '深圳',
    'shenzhen-baq': '深圳',
    'shenzhen-psq': '深圳',
    'shenzhen-gmq': '深圳',
    'shenzhen-luohuqu': '深圳',
    'shenzhen-lgq': '深圳',

    # ===== 广州 =====
    'guangzhou': '广州',
    'guangzhou-thq': '广州',
    'guangzhou-pyq': '广州',
    'guangzhou-zcq': '广州',

    # ===== 重庆 =====
    'chongqing': '重庆',
    'chongqing-naq': '重庆',
    'chongqing-yzq': '重庆',
    'chongqing-ljxq': '重庆',
    'chongqing-jlpq': '重庆',
    'chongqing-bbq': '重庆',
    'chongqing-bnq': '重庆',
    'chongqing-tnq': '重庆',
    'chongqing-tlq': '重庆',
    'chongqing-spbq': '重庆',
    'chongqing-ddkq': '重庆',
    'chongqing-bsq': '重庆',
    'chongqing-wzq': '重庆',

    # ===== 成都 =====
    'chengdu': '成都',
    'chengdu-chq': '成都',
    'chengdu-qyq': '成都',
    'chengdu-whq': '成都',
    'chengdu-wjq': '成都',
    'chengdu-slq': '成都',
    'chengdu-pdq': '成都',
    'chengdu-jjq': '成都',
    'chengdu-gxq': '成都',
    'chengdu-jnq': '成都',
    'chengdu-qbjq': '成都',

    # ===== 杭州 =====
    'hangzhou': '杭州',
    'hangzhou-scq': '杭州',
    'hangzhou-lpq': '杭州',
    'hangzhou-xhq': '杭州',
    'hangzhou-bjq': '杭州',
    'hangzhou-qtq': '杭州',
    'hangzhou-yhq': '杭州',
    'hangzhou-fyq': '杭州',
    'hangzhou-jgq': '杭州',
    'hangzhou-gsq': '杭州',
    'hangzhou-tlx': '杭州',
    'hangzhou-xsq': '杭州',

    # ===== 西安 =====
    'xian': '西安',
    'xian-ytq': '西安',
    'xian-bqq': '西安',
    'xian-xcq': '西安',

    # ===== 南京 =====
    'nanjing': '南京',
    'nanjing-qhq': '南京',
    'nanjing-jyq': '南京',
    'nanjing-xwq': '南京',
    'nanjing-jbxq': '南京',
    'nanjing-pkq': '南京',
    'nanjing-qxq': '南京',
    'nanjing-jnq': '南京',
    'nanjing-glq': '南京',
    'nanjing-yhtq': '南京',

    # ===== 武汉 =====
    'wuhan': '武汉',
    'wuhan-hsq': '武汉',

    # ===== 东莞 =====
    'dongguan': '东莞',
    'dongguan-hmz': '东莞',
    'dongguan-caz': '东莞',
    'dongguan-spz': '东莞',
    'dongguan-ncq': '东莞',
    'dongguan-hjz': '东莞',
    'dongguan-xgz': '东莞',
    'dongguan-wjq': '东莞',
    'dongguan-qsz': '东莞',
    'dongguan-qtz': '东莞',
    'dongguan-hj': '东莞',
    'dongguan-dkz': '东莞',
    'dongguan-qxz': '东莞',
    'dongguan-dlz': '东莞',
    'dongguan-dlsz': '东莞',
    'dongguan-sshq': '东莞',
    'dongguan-lbz': '东莞',
    'dongguan-csz': '东莞',
    'dongguan-hm': '东莞',
    'dongguan-slz': '东莞',
    'dongguan-sjz': '东莞',
    'dongguan-fgz': '东莞',
    'dongguan-hlz': '东莞',
    'dongguan-txz': '东莞',
    'dongguan-cxd': '东莞',
    'dongguan-dcq': '东莞',
    'dongguan-cpz': '东莞',

    # ===== 苏州 =====
    'suzhou': '苏州',
    'suzhou-gyyq': '苏州',
    'suzhou-xcq': '苏州',
    'suzhou-wzq': '苏州',
    'suzhou-gsq': '苏州',
    'suzhou-gxq': '苏州',
    'suzhou-wjq': '苏州',
    'suzhou-hq': '苏州',
    'kunshan': '苏州',
    'changshu': '苏州',
    'zhangjiagang': '苏州',
    'taicang': '苏州',

    # ===== 沈阳 =====
    'shenyang': '沈阳',
    'shenyang-hnq': '沈阳',
    'shenyang-hgq': '沈阳',

    # ===== 昆明 =====
    'kunming': '昆明',
    'kunming-plq': '昆明',
    'kunming-whq': '昆明',
    'kunming-xsq': '昆明',
    'kunming-jnq': '昆明',
    'kunming-gdq': '昆明',
    'kunming-cgq': '昆明',

    # ===== 大连 =====
    'dalian': '大连',
    'dalian-zsq': '大连',
    'dalian-gxyq': '大连',
    'dalian-xgq': '大连',
    'dalian-gjzq': '大连',
    'dalian-jzq': '大连',
    'dalian-shkq': '大连',
    'dalian-cxd': '大连',

    # ===== 天津 =====
    'tianjin': '天津',
    'tianjin-hpq': '天津',
    'tianjin-wqq': '天津',
    'tianjin-xqq': '天津',
    'tianjin-dlq': '天津',
    'tianjin-bdq': '天津',
    'tianjin-bhxq': '天津',
    'tianjin-hxq': '天津',
    'tianjin-nkq': '天津',
    'tianjin-bcq': '天津',
    'tianjin-jnq': '天津',
    'tianjin-hdq': '天津',

    # ===== 宁波 =====
    'ningbo': '宁波',
    'ningbo-jbq': '宁波',
    'ningbo-yzq': '宁波',
    'ningbo-gx': '宁波',
    'ningbo-blq': '宁波',
    'ningbo-yys': '宁波',
    'ningbo-nhx': '宁波',
    'ningbo-cxs': '宁波',
    'ningbo-zhq': '宁波',
    'ningbo-fhq': '宁波',
    'ningbo-hsq': '宁波',

    # ===== 郑州 =====
    'zhengzhou': '郑州',
    'zhengzhou-zzxq': '郑州',
    'zhengzhou-gxq': '郑州',
    'zhengzhou-jkq': '郑州',
    'guanchenghuizuqu': '郑州',
    'zhongyuanqu': '郑州',
    'jinshuiqu': '郑州',
    'xingyangshi': '郑州',
    'gongyishi': '郑州',

    # ===== 长沙 =====
    'changsha': '长沙',
    'changsha-txq': '长沙',
    'changsha-nxs': '长沙',
    'changsha-yhq': '长沙',
    'changsha-ylq': '长沙',
    'changsha-csx': '长沙',
    'changsha-kfq': '长沙',
    'changsha-frq': '长沙',

    # ===== 合肥 =====
    'hefei': '合肥',
    'hefei-fxx': '合肥',
    'hefei-xzq': '合肥',
    'hefei-ssq': '合肥',
    'hefei-lyq': '合肥',
    'hefei-bhq': '合肥',
    'hefei-jkq': '合肥',
    'hefei-chs': '合肥',
    'hefei-gxq': '合肥',

    # ===== 福州 =====
    'fuzhou': '福州',
    'fuzhou-tjq': '福州',
    'fuzhou-glq': '福州',
    'fuzhou-csq': '福州',
    'fuzhou-fqs': '福州',
    'fuzhou-jaq': '福州',
    'fuzhou-mhx': '福州',
    'fuzhou-clq': '福州',
    'fuzhou-ptx': '福州',
    'fuzhou-ljx': '福州',
    'fuzhou-mwq': '福州',
    'fuzhou-lyx': '福州',
    'fuzhou-mqx': '福州',

    # ===== 长春 =====
    'changchun': '长春',
    'changchun-lyq': '长春',
    'changchun-ngq': '长春',
    'changchun-kcq': '长春',
    'changchun-cyq': '长春',
    'changchun-edq': '长春',
    'changchun-jygxjs': '长春',
    'changchun-jjjs': '长春',
    'changchun-gxjs': '长春',

    # ===== 青岛 =====
    'qingdao': '青岛',
    'qingdao-cyq': '青岛',
    'qingdao-sbq': '青岛',
    'qingdao-hdq': '青岛',
    'qingdao-gxq': '青岛',
    'qingdao-lcq': '青岛',
    'qingdao-lsq': '青岛',
    'qingdao-snq': '青岛',
    'qingdao-pds': '青岛',
    'qingdao-jzs': '青岛',
    'qingdao-jmq': '青岛',

    # ===== 济南 =====
    'jinan': '济南',
    'jinan-lxq': '济南',
    'jinan-gxq': '济南',
    'jinan-jyq': '济南',
    'jinan-hyq': '济南',
    'jinan-szq': '济南',
    'jinan-zqq': '济南',
    'jinan-lcq': '济南',
    'jinan-gcq': '济南',
    'jinan-tqq': '济南',

    # ===== 哈尔滨 =====
    'harbin': '哈尔滨',
    'hadongbin': '哈尔滨',
    'hadongbin-ngq': '哈尔滨',
    'hadongbin-pfq': '哈尔滨',
    'hadongbin-dlq': '哈尔滨',
    'hadongbin-dwq': '哈尔滨',
    'hadongbin-sbq': '哈尔滨',

    # ===== 珠海 =====
    'zhuhai': '珠海',
    'zhuhai-glg': '珠海',

    # ===== 全国/远程 =====
    'all': '全国',
}

CITY_TIER = {
    '上海': '一线',
    '北京': '一线',
    '深圳': '一线',
    '广州': '一线',
    '成都': '新一线',
    '杭州': '新一线',
    '重庆': '新一线',
    '西安': '新一线',
    '苏州': '新一线',
    '武汉': '新一线',
    '南京': '新一线',
    '天津': '新一线',
    '东莞': '新一线',
    '长沙': '新一线',
    '郑州': '新一线',
    '青岛': '新一线',
    '宁波': '新一线',
    '昆明': '新一线',
    '大连': '二线',
    '合肥': '二线',
    '福州': '二线',
    '长春': '二线',
    '济南': '二线',
    '哈尔滨': '二线',
    '沈阳': '二线',
    '珠海': '二线',
    '全国': '其他',
}
